OLOZLO/algo-study

- src/_210105/boj10021/Main_1n9yun.java
- src/_210105/boj15591/Main_1n9yun.java
- src/_210105/prog17681/Main_1n9yun.java
- src/_210105/prog17682/Main_1n9yun.java
> 1n9yun 210105 숙제

- src/_210105/boj10021/Main_girawhale.java
- src/_210105/boj15591/Main_girawhale.java
- src/_210105/boj15591/Main_sh.java
- src/hash/prog42576/Main_girawhale.java
- src/hash/prog42577/Main_girawhale.java
- src/hash/prog42578/Main_girawhale.java
- src/hash/prog42579/Main_girawhale.java
> 210105 과제 업로드

- src/.idea/.gitignore
- src/.idea/misc.xml
- src/.idea/modules.xml
- src/.idea/src.iml
- src/.idea/vcs.xml
- src/_210105/boj10021/Main_ms.java
- src/_210105/boj15591/Main_ms.java
- src/_210105/prog17681/Main_ms.java
- src/_210105/prog17682/Main_ms.java
- src/algo-study.iml
> [MS] 21.01.04 UPDATE

- src/hash/prog42577/Main_girawhale.java
- src/stack_queue/prog42583/Main_girawhale.java
- src/stack_queue/prog42586/Main_girawhale.java
- src/stack_queue/prog42587/Main_girawhale.java
> [SH] Stack, Queue 추가

- src/_210112/boj18500/Main_1n9yun.java
- src/_210112/prog17677/Main_1n9yun.java
- src/_210112/prog17679/Main_1n9yun.java
> [1n9yun] 21.01.11 UPDATE

- src/_210112/boj16639/Main_girawhale.java
- src/_210112/boj18500/Main_girawhale.java
- src/_210112/prog17679/Main_girawhale.java
> 🐬 2021.01.12 과제 제출

- src/_210112/boj18500/Main_hz.java
- src/_210112/prog17677/Main_hz.java
- src/_210112/prog17679/Main_hz.java
> [HZ] 2주차 과제 제출

- src/_210112/boj18500/Main_hz.java
- src/_210112/prog17677/Main_hz.java
- src/_210112/prog17679/Main_hz.java
> [HZ] 210113HW 주석 추가

- src/_210119/boj14466/Main_hz.java
- src/_210119/prog17680/Main_hz.java
- src/_210119/prog17683/Main_hz.java
- src/stack_queue/prog42583/Main_hz.java
- src/stack_queue/prog42586/Main_hz.java
> 210119 숙제 완

- src/_210126/boj11437/Main_ms.java
- src/_210126/prog17684/Main_ms.java
- src/_210126/prog17684/Main_ms.js
- src/_210126/prog17686/Main_ms.java
- src/_210126/prog17686/Main_ms.js
- src/_210126/prog17687/Main_ms.java
- src/_210126/prog17687/Main_ms.js
> [MS] 21.01.25 UPDATE

- src/_210126/prog17686/Main_ms.java
> [MS] 21.01.26 UPDATE : 프로그래머스 [파일명 정렬] 코드 수정

- src/_210202/prog17678/Main_girawhale.java
> [SH] 21.01.31 UPDATE

- src/_210202/boj17837/Main_Taekyung2.java
- src/_210202/boj5827/Main_Taekyung2.java
- src/_210202/prog17676/Main_Taekyung2.java
- src/_210202/prog17678/Main_Taekyung2.java
> [TK] 21.02.01 UPDATE

- src/.idea/uiDesigner.xml
- src/_210202/boj17837/Main_ms.java
- src/_210202/prog17676/Main_ms.java
- src/_210202/prog17678/Main_ms.java
> [MS] 21.02.01 UPDATE

- src/_210202/boj5827/Main_Taekyung2.java
- src/_210209/boj1039/Main_Taekyung2.java
- src/_210209/boj9370/Main_Taekyung2.java
- src/_210209/prog17685/Main_Taekyung2.java
> [TK] 21.02.08 UPDATE

- src/_210216/boj1981/Main_girawhale.java
- src/_210216/boj2931/Main_girawhale.java
- src/_210216/prog42888/Main_girawhale.java
- src/_210216/prog42889/Main_girawhale.java
- src/_210216/prog42890/Main_girawhale.java
> [SH] 21.02.15 UPDATE

- src/_210302/boj16954/Main_girawhale.java
- src/_210302/boj1956/Main_girawhale.java
- src/_210302/prog42891/Main_girawhale.java
> [SH] 21.03.01 UPDATE

- src/_210309/boj16946/Main_girawhale.java
- src/_210309/boj2098/Main_girawhale.java
- src/_210309/prog60057/Main_girawhale.java
- src/_210309/prog60058/Main_girawhale.java
> [SH] 21.03.07 UPDATE

- src/_210316/boj3197/Main_girawhale.java
- src/_210316/boj5213/Main_girawhale.java
- src/_210316/prog60059/Main_girawhale.java
- src/_210316/prog60061/Main_girawhale.java
> 21.03.16 UPDATE

- src/_210406/boj1103/Main_hz.java
- src/_210406/boj17953/Main_hz.java
- src/_210406/boj19583/Main_hz.java
> [HZ] 21.04.06 UPDATE

- src/_210406/boj1103/Main_ms.java
- src/_210406/boj17953/Main_ms.java
- src/_210406/boj19583/Main_ms.java
> [MS] 21.04.06 HW UPDATE

- src/_210406/boj1103/Main_ja.java
- src/_210406/boj17953/Main_ja.java
- src/_210406/boj19583/Main_ja.java
> [JA] 21.04.06 HW UPDATE

- src/_210413/boj1052/Main_girawhale.java
- src/_210413/boj17143/Main_girawhale.java
- src/_210413/boj1939/Main_girawhale.java
내가 이거때문에.... class를 만들었숨미다...
후....
> [SH] 21.04.12 과제 업로드

- src/_210413/boj1052/Main_Taekyung2.java
- src/_210413/boj17143/Main_Taekyung2.java
- src/_210413/boj1939/Main_Taekyung2.java
> [TK] 21.04.13 HW

- src/_210413/boj1052/Main_jyj.java
- src/_210413/boj19939/Main_jyj.java
> [YJ] HOMEWORK

- src/_210413/boj1052/Main_ja.java
- src/_210413/boj17143/Main_ja.java
- src/_210413/boj1939/Main_ja.java
> [JA] 21.04.13 HW

- src/_210413/boj1052/Main_ms.java
- src/_210413/boj17143/Main_ms.java
- src/_210413/boj1939/Main_ms.java
> [MS] 21.04.13 과제 업로드

- src/_210420/boj20440/Main_ms.java
- src/_210420/boj2469/Main_ms.java
> [MS] 21.04.20 UPDATE

- src/_210413/boj1939/Main_jyj.java
- src/_210420/boj2469/Main_jyj.java
> [YJ] 21.04.20 TEST

- src/_210420/boj20440/Main_hz.java
- src/_210420/boj2469/Main_hz.java
제출에 의의를 두고 우선 올렸습니다😥
리뷰 안해주셔도 되고 수정하는 데로 다시 올리겠습니다🙏
boj2469_사다리 타기 수정해서 제출했습니당~
> [HZ] 21.04.20 TEST

- src/_210420/boj20440/Main_girawhale.java
- src/_210420/boj2469/Main_girawhale.java
> [SH] 21.04.20 UPDATE

- src/_210420/boj20440/Main_ja.java
- src/_210420/boj2469/Main_ja.java
> [JA] 21.04.20 HW - 틀렸습니다!

- src/_210420/boj20440/Main_Taekyung2.java
- src/_210420/boj2469/Main_Taekyung2.java
- src/_210420/boj4574/Main_Taekyung2.java
> [TK]HW 21.04.20

- src/_210427/boj1072/Main_ms.java
- src/_210427/boj20952/Main_ms.java
이번 주 리뷰는 면접 준비로 못할 수도 있습니당.. 그냥 제 거는 읽고 넘어가주셔도 됩니당.
> [MS] 21.04.27 UPDATE

- src/_210427/boj1072/Main_ja.java
- src/_210427/boj20952/Main_ja.java
이번 주도 망했습니다 ㅠㅡㅠ
다시 도전해서 올려 볼게여! 😂😂
> [JA] 21.04.28 HW

- src/_210427/boj1072/Main_girawhale.java
늦어서 죄송함다.....
sns 문제는 아예 다른 방식으로 풀다가 잘못된거 반례 찾고 아예 접근이 잘못됐다는 걸 알아서 빼고 올립니당...
> 🐳 21.04.27 과제 제출

- src/_210427/boj1072/Main_hz.java
- src/_210427/boj20952/Main_hz.java
> [HZ] 21.04.27 TEST

- src/_210427/boj1072/Main_jyj.java
> [YJ] 21.04.29

- src/_210504/boj12764/Main_hz.java
- src/_210504/boj12886/Main_hz.java
- src/_210504/boj15905/Main_hz.java
> [HZ] 21.05.04 TEST

- src/_210504/boj12764/Main_ms.java
- src/_210504/boj12886/Main_ms.java
- src/_210504/boj15905/Main_ms.java
> [MS] 21.05.04 UPDATE

- src/_210504/boj12764/Main_Taekyung2.java
- src/_210504/boj12886/Main_Taekyung2.java
- src/_210504/boj15905/Main_Taekyung2.java
> [TK]21.05.04 homework

- src/_210504/boj12764/Main_ja.java
- src/_210504/boj12886/Main_ja.java
- src/_210504/boj15905/Main_ja.java
> [JA] 21.05.04 HW

- src/_210511/boj20166/Main_girawhale.java
- src/_210511/boj6236/Main_girawhale.java
택배 문제는 보다가 이건 내가 절대 풀수 없는 문제라고 생각하고 답보고 풀엇슴다...
> 🐳 21.05.11 과제 제출

- src/_210511/boj20166/Main_ms.java
- src/_210511/boj6326/Main_ms.java
> [MS] 21.05.11 UPDATE

- src/_210511/boj20166/Main_hz.java
- src/_210511/boj2636/Main_hz.java
> [HZ] 21.05.11 TEST

- src/_210511/boj6236/Main_hz.java
- src/_210518/boj1599/Main_hz.java
- src/_210518/boj2257/Main_hz.java
> [HZ] 21.05.18 TEST

- src/_210518/boj11967/Main_ja.java
- src/_210518/boj1599/Main_ja.java
- src/_210518/boj2257/Main_ja.java
> [JA] 21.05.18 HW

- src/_210511/boj6236/Main_ms.java
- src/_210518/boj11967/Main_ms.java
- src/_210518/boj1599/Main_ms.java
- src/_210518/boj2257/Main_ms.java
- src/_210518/boj2257/Main_ms2.java
> [MS] 21.05.18 UPDATE

- src/_210525/boj14718/Main_hz.java
- src/_210525/boj15658/Main_hz.java
- src/_210525/boj6593/Main_hz.java
> [HZ] 21.05.25 TEST

- src/_210525/boj14718/Main_girawhale.java
- src/_210525/boj15658/Main_girawhale.java
- src/_210525/boj6593/Main_girawhale.java
> 🐳 21.05.25 UPDATE

- src/_210525/boj14718/Main_Taekyung2.java
- src/_210525/boj15658/Main_Taekyung2.java
- src/_210525/boj6593/Main_Taekyung2.java
> [TK]21.05.25

- src/_210518/boj11967/Main_ja.java
- src/_210525/boj14718/Main_ja.java
- src/_210525/boj15658/Main_ja.java
- src/_210525/boj6593/Main_ja.java
> [JA] 21.05.25 HW

- src/_210601/boj20040/Main_ms.java
- src/_210601/boj2529/Main_ms.java
- src/_210601/boj2571/Main_ms.java
> [MS] 21.06.01 UPDATE

- src/_210601/boj20040/Main_girawhale.java
- src/_210601/boj2529/Main_girawhale.java
> [SH] 21.06.01 UPDATE

- src/_210601/boj20040/Main_ja.java
- src/_210601/boj2529/Main_ja.java
> [JA] 21.06.01 HW - 부등호

- src/_210608/boj10800/Main_Taekyung2.java
- src/_210608/boj11985/Main_Taekyung2.java
- src/_210608/boj1669/Main_Taekyung2.java
> [TK] 21.06.08 hw

- src/_210608/boj11985/Main_ms.java
- src/_210608/boj1669/Main_ms.java
> [MS] 21.06.08 UPDATE

- src/_210601/_210608/boj1669/Main_girawhale.java
컬러볼은 하긴 했는데, 음... 참고를 조금 해서 뺏슴다...
> 🐳 21.06.08 과제

- src/_210608/boj1669/Main_girawhale.java
- src/_210615/boj17616/Main_girawhale.java
- src/_210615/boj18430/Main_girawhale.java
> [SH] 21.06.15 UPDATE

- src/_210615/boj17616/Main_hz.java
- src/_210615/boj18430/Main_hz.java
늦어서 죄송함다...
당일에 커밋은 했는데... PR을 까먹었어요...😅
> [HZ] 21.06.15 TEST
